### ISSUE TITLE
new base names: __nwa and __dla

### ISSUE THREAD

**Issue by LRFLEW** [Chadderz121/ghs-demangle#2]
I've been looking at the disassembly of Hachi (Nintendo's official DS emulator for Wii U), which includes function symbols. While checking what base names labeled as "have not been seen" are present (for the other issue), I identified two new base names that aren't in `Program.cs`. These are `__nwa` for `operator new[]` and `__dla` for `operator delete[]`.

Identifying that these are the correct demangled names for these base names was fairly tricky. The function signatures for them match. `__nwa__FUi` matches `operator new[](size_t)` the same way that `__nw__FUi` matches `operator new(size_t)`, and `__dla__FPv` matches `operator delete[](void*)` the same way that `__dl__FPv` matches `operator delete(void*)`. The implementations of `__nwa__FUi` and `__dla__FPv` simply perform a tail call to `__nw__FUi` and `__dl__FPv` respectively.

To ensure I had this correct, I looked at where `__nwa_FUi` was being called. Most of Hachi uses its own allocator(s), so this is mostly only used for classes in the standard library. I found two calls to it in the function `_Init__Q2_3std85time_get__tm__69_cQ2_3std58istreambuf_iterator__tm__31_cQ2_3std20char_traits__tm__2_cFRCQ2_3std8_Locinfo_v` (which I assume is a function called by the inlined constructor for `std::time_get`) which uses it to implement what is essentially `strdup`. It calls `strlen` on a string constant, allocates that length plus one, and copies the constant string to the new buffer. This is a reasonable use case for `operator new[]`, so I feel this is good enough evidence to confirm that `__nwa` means `operator new[]`. These two buffers are deallocated in `__dt__Q2_3std85time_get__tm__69_cQ2_3std58istreambuf_iterator__tm__31_cQ2_3std20char_traits__tm__2_cFv` with `__dla_FPv`, which matches with it being `operator delete[]` if the allocator is `operator new[]`.

**Comment by Chadderz121** [comment]
Many thanks for the thorough research. I've incorporated your suggestions in 3f1a9f687efa39dc082af1f5aea51444a4c72d01 and pushed a release of v1.1.0 which incorporates these changes.
